using System;
using System.Collections.Generic;
using System.Text;
using YC_ChroZenGC_Type;

namespace ChroZenService
{
    public static class DataManager
    {
        public static class RunState
        {
            public static bool IsDeviceRun;
            public enum E_CHART_DRAW_STATE
            {
                DRAW,
                STOP
            }
            public static E_CHART_DRAW_STATE e_CHART_DRAW_STATE = E_CHART_DRAW_STATE.STOP;
        }

        #region Received

        public static T_PACKCODE_CHROZEN_SYSTEM_INFORM t_PACKCODE_CHROZEN_SYSTEM_INFORM_Received = T_PACKCODE_CHROZEN_SYSTEM_INFORMManager.InitiatedInstance;
        public static T_PACKCODE_CHROZEN_SYSTEM_CONFIG t_PACKCODE_CHROZEN_SYSTEM_CONFIG_Received = T_PACKCODE_CHROZEN_SYSTEM_CONFIGManager.InitiatedInstance;
        public static T_PACKCODE_CHROZEN_OVEN_SETTING t_PACKCODE_CHROZEN_OVEN_SETTING_Received = T_PACKCODE_CHROZEN_OVEN_SETTINGManager.InitiatedInstance;

        public static T_PACKCODE_CHROZEN_INLET_SETTING t_PACKCODE_CHROZEN_INLET_SETTING_Front_Received = T_PACKCODE_CHROZEN_INLET_SETTINGManager.InitiatedInstance;
        public static T_PACKCODE_CHROZEN_INLET_SETTING t_PACKCODE_CHROZEN_INLET_SETTING_Center_Received = T_PACKCODE_CHROZEN_INLET_SETTINGManager.InitiatedInstance;
        public static T_PACKCODE_CHROZEN_INLET_SETTING t_PACKCODE_CHROZEN_INLET_SETTING_Rear_Received = T_PACKCODE_CHROZEN_INLET_SETTINGManager.InitiatedInstance;

        public static T_PACKCODE_CHROZEN_DET_SETTING t_PACKCODE_CHROZEN_DET_SETTING_Front_Received = T_PACKCODE_CHROZEN_DET_SETTINGManager.InitiatedInstance;
        public static T_PACKCODE_CHROZEN_DET_SETTING t_PACKCODE_CHROZEN_DET_SETTING_Center_Received = T_PACKCODE_CHROZEN_DET_SETTINGManager.InitiatedInstance;
        public static T_PACKCODE_CHROZEN_DET_SETTING t_PACKCODE_CHROZEN_DET_SETTING_Rear_Received = T_PACKCODE_CHROZEN_DET_SETTINGManager.InitiatedInstance;

        public static T_PACKCODE_CHROZEN_VALVE_SETTING t_PACKCODE_CHROZEN_VALVE_SETTING_Received = T_PACKCODE_CHROZEN_VALVE_SETTINGManager.InitiatedInstance;
        public static T_PACKCODE_CHROZEN_AUX_TEMP_SETTING t_PACKCODE_CHROZEN_AUX_TEMP_SETTING_Received = T_PACKCODE_CHROZEN_AUX_TEMP_SETTINGManager.InitiatedInstance;

        public static T_PACKCODE_CHROZEN_AUX_APC_SETTING t_PACKCODE_CHROZEN_AUX_APC_SETTING_Front_Received = T_PACKCODE_CHROZEN_AUX_APC_SETTINGManager.InitiatedInstance;
        public static T_PACKCODE_CHROZEN_AUX_APC_SETTING t_PACKCODE_CHROZEN_AUX_APC_SETTING_Center_Received = T_PACKCODE_CHROZEN_AUX_APC_SETTINGManager.InitiatedInstance;
        public static T_PACKCODE_CHROZEN_AUX_APC_SETTING t_PACKCODE_CHROZEN_AUX_APC_SETTING_Rear_Received = T_PACKCODE_CHROZEN_AUX_APC_SETTINGManager.InitiatedInstance;

        public static T_PACKCODE_CHROZEN_DET_SIGNAL_SETTING t_PACKCODE_CHROZEN_DET_SIGNAL_SETTING_Front_Received = T_PACKCODE_CHROZEN_DET_SIGNAL_SETTINGManager.InitiatedInstance;
        public static T_PACKCODE_CHROZEN_DET_SIGNAL_SETTING t_PACKCODE_CHROZEN_DET_SIGNAL_SETTING_Center_Received = T_PACKCODE_CHROZEN_DET_SIGNAL_SETTINGManager.InitiatedInstance;
        public static T_PACKCODE_CHROZEN_DET_SIGNAL_SETTING t_PACKCODE_CHROZEN_DET_SIGNAL_SETTING_Rear_Received = T_PACKCODE_CHROZEN_DET_SIGNAL_SETTINGManager.InitiatedInstance;

        public static T_PACKCODE_CHROZEN_SPECIAL_FUNCTION t_PACKCODE_CHROZEN_SPECIAL_FUNCTION_Received = T_PACKCODE_CHROZEN_SPECIAL_FUNCTIONManager.InitiatedInstance;
        public static T_PACKCODE_CHROZEN_TIME_CTRL_SETTING t_PACKCODE_CHROZEN_TIME_CTRL_SETTING_Received = T_PACKCODE_CHROZEN_TIME_CTRL_SETTINGManager.InitiatedInstance;
        public static T_PACKCODE_CHROZEN_SYSTEM_STATE t_PACKCODE_CHROZEN_SYSTEM_STATE_Received = T_PACKCODE_CHROZEN_SYSTEM_STATEManager.InitiatedInstance;
        public static T_PACKCODE_CHROZEN_SLFEMSG t_PACKCODE_CHROZEN_SLFEMSG_Received = T_PACKCODE_CHROZEN_SLFEMSGManager.InitiatedInstance;
        public static T_PACKCODE_CHROZEN_COMMAND t_PACKCODE_CHROZEN_COMMAND_Received = T_PACKCODE_CHROZEN_COMMANDManager.InitiatedInstance;
        public static T_PACKCODE_CHROZEN_SIGNAL t_PACKCODE_CHROZEN_SIGNAL_Received = T_PACKCODE_CHROZEN_SIGNALManager.InitiatedInstance;

        #region LCD

        public static T_PACKCODE_CHROZEN_LCD_APC_CALIB_READ T_PACKCODE_CHROZEN_LCD_APC_CALIB_READ_Received = T_PACKCODE_CHROZEN_LCD_APC_CALIB_READManager.InitiatedInstance;
        public static T_PACKCODE_CHROZEN_LCD_APC_SENSOR_VOLTAGE T_PACKCODE_CHROZEN_LCD_APC_SENSOR_VOLTAGE_Received = T_PACKCODE_CHROZEN_LCD_APC_SENSOR_VOLTAGEManager.InitiatedInstance;
        public static T_PACKCODE_CHROZEN_LCD_DIAG T_PACKCODE_CHROZEN_LCD_DIAG_Received = T_PACKCODE_CHROZEN_LCD_DIAGManager.InitiatedInstance;
        public static T_PACKCODE_CHROZEN_LCD_SIGNAL T_PACKCODE_CHROZEN_LCD_SIGNAL_Received = T_PACKCODE_CHROZEN_LCD_SIGNALManager.InitiatedInstance;
        public static T_PACKCODE_CHROZEN_LCD_VOLTAGE_CHECK T_PACKCODE_CHROZEN_LCD_VOLTAGE_CHECK_Received = T_PACKCODE_CHROZEN_LCD_VOLTAGE_CHECKManager.InitiatedInstance;
        public static T_PACKCODE_LCD_COMMAND T_PACKCODE_LCD_COMMAND_Received = T_PACKCODE_LCD_COMMANDManager.InitiatedInstance;
        public static T_PACKCODE_LCD_COMMAND_TYPE_AUX T_PACKCODE_LCD_COMMAND_TYPE_AUX_Received = T_PACKCODE_LCD_COMMAND_TYPE_AUXManager.InitiatedInstance;
        public static T_PACKCODE_LCD_COMMAND_TYPE_AUXTEMP T_PACKCODE_LCD_COMMAND_TYPE_AUXTEMP_Received = T_PACKCODE_LCD_COMMAND_TYPE_AUXTEMPManager.InitiatedInstance;
        public static T_PACKCODE_LCD_COMMAND_TYPE_DET T_PACKCODE_LCD_COMMAND_TYPE_DET_Received = T_PACKCODE_LCD_COMMAND_TYPE_DETManager.InitiatedInstance;
        public static T_PACKCODE_LCD_COMMAND_TYPE_INLET T_PACKCODE_LCD_COMMAND_TYPE_INLET_Received = T_PACKCODE_LCD_COMMAND_TYPE_INLETManager.InitiatedInstance;
        public static T_PACKCODE_LCD_COMMAND_TYPE_SIGNAL T_PACKCODE_LCD_COMMAND_TYPE_SIGNAL_Received = T_PACKCODE_LCD_COMMAND_TYPE_SIGNALManager.InitiatedInstance;
        public static T_PACKCODE_LCD_COMMAND_TYPE_TEMP T_PACKCODE_LCD_COMMAND_TYPE_TEMP_Received = T_PACKCODE_LCD_COMMAND_TYPE_TEMPManager.InitiatedInstance;

        #endregion LCD

        #endregion Received

        #region Sent

        public static T_PACKCODE_CHROZEN_SYSTEM_INFORM t_PACKCODE_CHROZEN_SYSTEM_INFORM_Send = T_PACKCODE_CHROZEN_SYSTEM_INFORMManager.InitiatedInstance;
        public static T_PACKCODE_CHROZEN_SYSTEM_CONFIG t_PACKCODE_CHROZEN_SYSTEM_CONFIG_Send = T_PACKCODE_CHROZEN_SYSTEM_CONFIGManager.InitiatedInstance;
        public static T_PACKCODE_CHROZEN_OVEN_SETTING t_PACKCODE_CHROZEN_OVEN_SETTING_Send = T_PACKCODE_CHROZEN_OVEN_SETTINGManager.InitiatedInstance;

        public static T_PACKCODE_CHROZEN_INLET_SETTING t_PACKCODE_CHROZEN_INLET_SETTING_Front_Send = T_PACKCODE_CHROZEN_INLET_SETTINGManager.InitiatedInstance;
        public static T_PACKCODE_CHROZEN_INLET_SETTING t_PACKCODE_CHROZEN_INLET_SETTING_Center_Send = T_PACKCODE_CHROZEN_INLET_SETTINGManager.InitiatedInstance;
        public static T_PACKCODE_CHROZEN_INLET_SETTING t_PACKCODE_CHROZEN_INLET_SETTING_Rear_Send = T_PACKCODE_CHROZEN_INLET_SETTINGManager.InitiatedInstance;

        public static T_PACKCODE_CHROZEN_DET_SETTING t_PACKCODE_CHROZEN_DET_SETTING_Front_Send = T_PACKCODE_CHROZEN_DET_SETTINGManager.InitiatedInstance;
        public static T_PACKCODE_CHROZEN_DET_SETTING t_PACKCODE_CHROZEN_DET_SETTING_Center_Send = T_PACKCODE_CHROZEN_DET_SETTINGManager.InitiatedInstance;
        public static T_PACKCODE_CHROZEN_DET_SETTING t_PACKCODE_CHROZEN_DET_SETTING_Rear_Send = T_PACKCODE_CHROZEN_DET_SETTINGManager.InitiatedInstance;

        public static T_PACKCODE_CHROZEN_VALVE_SETTING t_PACKCODE_CHROZEN_VALVE_SETTING_Send = T_PACKCODE_CHROZEN_VALVE_SETTINGManager.InitiatedInstance;
        public static T_PACKCODE_CHROZEN_AUX_TEMP_SETTING t_PACKCODE_CHROZEN_AUX_TEMP_SETTING_Send = T_PACKCODE_CHROZEN_AUX_TEMP_SETTINGManager.InitiatedInstance;

        public static T_PACKCODE_CHROZEN_AUX_APC_SETTING t_PACKCODE_CHROZEN_AUX_APC_SETTING_Front_Send = T_PACKCODE_CHROZEN_AUX_APC_SETTINGManager.InitiatedInstance;
        public static T_PACKCODE_CHROZEN_AUX_APC_SETTING t_PACKCODE_CHROZEN_AUX_APC_SETTING_Center_Send = T_PACKCODE_CHROZEN_AUX_APC_SETTINGManager.InitiatedInstance;
        public static T_PACKCODE_CHROZEN_AUX_APC_SETTING t_PACKCODE_CHROZEN_AUX_APC_SETTING_Rear_Send = T_PACKCODE_CHROZEN_AUX_APC_SETTINGManager.InitiatedInstance;

        public static T_PACKCODE_CHROZEN_DET_SIGNAL_SETTING t_PACKCODE_CHROZEN_DET_SIGNAL_SETTING_Front_Send = T_PACKCODE_CHROZEN_DET_SIGNAL_SETTINGManager.InitiatedInstance;
        public static T_PACKCODE_CHROZEN_DET_SIGNAL_SETTING t_PACKCODE_CHROZEN_DET_SIGNAL_SETTING_Center_Send = T_PACKCODE_CHROZEN_DET_SIGNAL_SETTINGManager.InitiatedInstance;
        public static T_PACKCODE_CHROZEN_DET_SIGNAL_SETTING t_PACKCODE_CHROZEN_DET_SIGNAL_SETTING_Rear_Send = T_PACKCODE_CHROZEN_DET_SIGNAL_SETTINGManager.InitiatedInstance;

        public static T_PACKCODE_CHROZEN_SPECIAL_FUNCTION t_PACKCODE_CHROZEN_SPECIAL_FUNCTION_Send = T_PACKCODE_CHROZEN_SPECIAL_FUNCTIONManager.InitiatedInstance;
        public static T_PACKCODE_CHROZEN_TIME_CTRL_SETTING t_PACKCODE_CHROZEN_TIME_CTRL_SETTING_Send = T_PACKCODE_CHROZEN_TIME_CTRL_SETTINGManager.InitiatedInstance;
        public static T_PACKCODE_CHROZEN_SYSTEM_STATE t_PACKCODE_CHROZEN_SYSTEM_STATE_Send = T_PACKCODE_CHROZEN_SYSTEM_STATEManager.InitiatedInstance;
        public static T_PACKCODE_CHROZEN_SLFEMSG t_PACKCODE_CHROZEN_SLFEMSG_Send = T_PACKCODE_CHROZEN_SLFEMSGManager.InitiatedInstance;
        public static T_PACKCODE_CHROZEN_COMMAND t_PACKCODE_CHROZEN_COMMAND_Send = T_PACKCODE_CHROZEN_COMMANDManager.InitiatedInstance;
        public static T_PACKCODE_CHROZEN_SIGNAL t_PACKCODE_CHROZEN_SIGNAL_Send = T_PACKCODE_CHROZEN_SIGNALManager.InitiatedInstance;

        #region LCD

        public static T_PACKCODE_CHROZEN_LCD_APC_CALIB_READ T_PACKCODE_CHROZEN_LCD_APC_CALIB_READ_Send = T_PACKCODE_CHROZEN_LCD_APC_CALIB_READManager.InitiatedInstance;
        public static T_PACKCODE_CHROZEN_LCD_APC_SENSOR_VOLTAGE T_PACKCODE_CHROZEN_LCD_APC_SENSOR_VOLTAGE_Send = T_PACKCODE_CHROZEN_LCD_APC_SENSOR_VOLTAGEManager.InitiatedInstance;
        public static T_PACKCODE_CHROZEN_LCD_DIAG T_PACKCODE_CHROZEN_LCD_DIAG_Send = T_PACKCODE_CHROZEN_LCD_DIAGManager.InitiatedInstance;
        public static T_PACKCODE_CHROZEN_LCD_SIGNAL T_PACKCODE_CHROZEN_LCD_SIGNAL_Send = T_PACKCODE_CHROZEN_LCD_SIGNALManager.InitiatedInstance;
        public static T_PACKCODE_CHROZEN_LCD_VOLTAGE_CHECK T_PACKCODE_CHROZEN_LCD_VOLTAGE_CHECK_Send = T_PACKCODE_CHROZEN_LCD_VOLTAGE_CHECKManager.InitiatedInstance;
        public static T_PACKCODE_LCD_COMMAND T_PACKCODE_LCD_COMMAND_Send = T_PACKCODE_LCD_COMMANDManager.InitiatedInstance;
        public static T_PACKCODE_LCD_COMMAND_TYPE_AUX T_PACKCODE_LCD_COMMAND_TYPE_AUX_Send = T_PACKCODE_LCD_COMMAND_TYPE_AUXManager.InitiatedInstance;
        public static T_PACKCODE_LCD_COMMAND_TYPE_AUXTEMP T_PACKCODE_LCD_COMMAND_TYPE_AUXTEMP_Send = T_PACKCODE_LCD_COMMAND_TYPE_AUXTEMPManager.InitiatedInstance;
        public static T_PACKCODE_LCD_COMMAND_TYPE_DET T_PACKCODE_LCD_COMMAND_TYPE_DET_Send = T_PACKCODE_LCD_COMMAND_TYPE_DETManager.InitiatedInstance;
        public static T_PACKCODE_LCD_COMMAND_TYPE_INLET T_PACKCODE_LCD_COMMAND_TYPE_INLET_Send = T_PACKCODE_LCD_COMMAND_TYPE_INLETManager.InitiatedInstance;
        public static T_PACKCODE_LCD_COMMAND_TYPE_SIGNAL T_PACKCODE_LCD_COMMAND_TYPE_SIGNAL_Send = T_PACKCODE_LCD_COMMAND_TYPE_SIGNALManager.InitiatedInstance;
        public static T_PACKCODE_LCD_COMMAND_TYPE_TEMP T_PACKCODE_LCD_COMMAND_TYPE_TEMP_Send = T_PACKCODE_LCD_COMMAND_TYPE_TEMPManager.InitiatedInstance;

        #endregion LCD

        #endregion Sent
    }
}
